spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  thymeleaf:
    cache: false
server:
  port: 8080

sqltemplate:
  autoload: true
  dialect: mysql